version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5050
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    environment:
      - DJANGO_SETTINGS_MODULE=wol_docker.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
