version: '3.8'

services:
  django:
    image: yuris127/wol_docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:5050
    volumes:
      - ./:/app
    ports:
      - "5050:5050"
    environment:
      - DJANGO_SETTINGS_MODULE=wol_docker.settings
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
